<?php

	define("P_DIR_NAME",        "");
	define("P_HOMEPAGE_URL",    "http://127.0.0.1/");
	define("P_SCRIPT_ROOT",     $_SERVER['DOCUMENT_ROOT']."/".P_DIR_NAME);
	define("DEFAULT_LANGUAGE",	"GB2312");
	
	
	define("hostname", "localhost" );
	define("dbuser", "root");
	define("dbpass", "homeworksystem");
	define("dbname", "d_homeworksystem");
	
	//分页查询每页的数据数量
	define("NUM_OF_ONE_PAGE_ACTIVITY", 5);
	define("NUM_OF_ONE_PAGE_SUB", 5);
	define("NUM_OF_ONE_PAGE_PAPER", 5);
	define("NUM_OF_ONE_PAGE_QUESTION", 5);
?>